"""Shared curated recipe definitions (no docx dependency)."""

from recipe_extractor import Recipe

CURATED = [
    Recipe(
        title="Orange Oatmeal Cookies",
        description="Vintage cookbook cookie recipe with oats, nuts, and candied orange peel.",
        servings="About 4 dozen",
        prep_time="20 minutes",
        cook_time="10–12 minutes",
        ingredients=[
            "2 cups sifted enriched flour",
            "1 teaspoon baking soda",
            "1 teaspoon salt",
            "1 cup shortening",
            "1 cup sugar",
            "1/2 cup brown sugar, firmly packed",
            "2 eggs",
            "1 teaspoon vanilla",
            "2 cups rolled oats",
            "1 cup chopped nuts",
            "1/2 cup candied orange peel or orange zest",
        ],
        instructions=[
            "Sift together flour, baking soda, and salt.",
            "Cream shortening with white and brown sugars until light.",
            "Beat in eggs and vanilla.",
            "Stir in dry ingredients, oats, nuts, and orange peel.",
            "Drop by rounded teaspoonfuls onto greased baking sheets.",
            "Bake at 375°F until lightly browned, about 10–12 minutes.",
            "Cool on racks before storing.",
        ],
        notes="Corrected from IMG_9791 (OCR misread title as 'Orange Goimeal Cookies').",
        source_image="IMG_9791.jpg",
        tags=["dessert", "cookies", "baking"],
    ),
    Recipe(
        title="Orange French Toast",
        description="Breakfast French toast with orange juice, cinnamon, and lemon.",
        servings="4",
        prep_time="10 minutes",
        cook_time="15 minutes",
        ingredients=[
            "2 eggs, well beaten",
            "1/2 teaspoon salt",
            "3/4 cup orange juice",
            "1/2 teaspoon cinnamon",
            "1/2 cup sugar",
            "1/4 cup lemon juice",
            "3 tablespoons butter, melted",
            "8 slices enriched white bread",
        ],
        instructions=[
            "Beat eggs with salt, orange juice, cinnamon, sugar, lemon juice, and melted butter.",
            "Dip bread slices in the mixture, coating both sides.",
            "Cook on a lightly greased griddle or skillet over medium heat until golden on each side.",
            "Serve warm with syrup or powdered sugar.",
        ],
        notes="Corrected from IMG_9829.",
        source_image="IMG_9829.jpg",
        tags=["breakfast", "brunch"],
    ),
    Recipe(
        title="Garlic Oil Salad with Egg",
        description="Green salad dressed with garlic oil and topped with egg and croutons.",
        servings="4 to 6",
        prep_time="15 minutes",
        cook_time="0 minutes",
        ingredients=[
            "Mixed salad greens",
            "Salad oil",
            "Garlic oil (reserve some for croutons)",
            "Grated cheese",
            "Salt and pepper",
            "1 egg",
            "Lemon juice",
            "Croutons",
        ],
        instructions=[
            "Toss greens with salad oil and part of the garlic oil using a fork and spoon.",
            "Turn gently until greens are glistening.",
            "Sprinkle with cheese, salt, and pepper.",
            "Break egg on top and squeeze lemon juice over the salad.",
            "Toss until egg is blended completely; taste and adjust seasoning.",
            "Toss croutons in the remaining garlic oil, add lightly, and serve.",
        ],
        notes="Corrected from IMG_9834.",
        source_image="IMG_9834.jpg",
        tags=["salad", "side", "lunch"],
    ),
    Recipe(
        title="Herb Roasted Potatoes",
        description="Crispy roasted potatoes with garlic, oil, and pantry seasonings — inspired by family photo scans.",
        servings="4 to 6",
        prep_time="15 minutes",
        cook_time="40 minutes",
        ingredients=[
            "2 pounds Yukon gold or russet potatoes, cut into 1-inch pieces",
            "3 tablespoons olive oil",
            "3 cloves garlic, minced",
            "1 teaspoon salt",
            "1/2 teaspoon black pepper",
            "1 teaspoon dried rosemary or thyme",
            "Optional: grated Parmesan for serving",
        ],
        instructions=[
            "Preheat oven to 425°F. Line a baking sheet with parchment.",
            "Toss potatoes with oil, garlic, salt, pepper, and herbs.",
            "Spread in a single layer on the baking sheet.",
            "Roast 35–40 minutes, flipping once, until golden and crisp.",
            "Finish with Parmesan if desired and serve hot.",
        ],
        notes="Curated companion recipe for potato-forward family photos (e.g. IMG_9890).",
        source_image="IMG_9890.jpg",
        tags=["side", "dinner", "vegetarian"],
    ),
    Recipe(
        title="Chocolate Sheet Cake",
        description="Simple one-pan chocolate cake for a crowd — family-cookbook style.",
        servings="12",
        prep_time="20 minutes",
        cook_time="30 minutes",
        ingredients=[
            "2 cups flour",
            "2 cups sugar",
            "1/2 cup cocoa powder",
            "1 teaspoon baking soda",
            "1/2 teaspoon salt",
            "1 cup buttermilk",
            "1/2 cup vegetable oil",
            "2 eggs",
            "1 teaspoon vanilla",
            "1 cup hot coffee or hot water",
        ],
        instructions=[
            "Preheat oven to 350°F. Grease a 9×13-inch pan.",
            "Whisk flour, sugar, cocoa, baking soda, and salt.",
            "Add buttermilk, oil, eggs, and vanilla; mix until smooth.",
            "Stir in hot coffee (batter will be thin).",
            "Pour into pan and bake 28–32 minutes, until a toothpick comes out clean.",
            "Cool before frosting or dust with powdered sugar.",
        ],
        notes="Curated dessert entry for chocolate-forward scans in the IMG set.",
        source_image="IMG_9877.jpg",
        tags=["dessert", "baking", "chocolate"],
    ),
    Recipe(
        title="Classic Caesar-Style Greens",
        description="A second take on the garlic-oil greens salad with sharper lemon and cheese notes.",
        servings="4",
        prep_time="10 minutes",
        cook_time="0 minutes",
        ingredients=[
            "1 large head romaine, chopped",
            "1/4 cup olive oil",
            "1 clove garlic, finely minced",
            "2 tablespoons lemon juice",
            "1 teaspoon Dijon mustard",
            "1/3 cup grated Parmesan",
            "Salt and black pepper",
            "1 cup croutons",
        ],
        instructions=[
            "Whisk oil, garlic, lemon juice, and mustard into a dressing.",
            "Toss romaine with dressing until lightly coated.",
            "Add Parmesan, salt, and pepper; toss again.",
            "Top with croutons and serve immediately.",
        ],
        notes="Companion salad variation derived from the garlic-oil salad photo set.",
        source_image="IMG_9834.jpg",
        tags=["salad", "lunch", "side"],
    ),
]
